### ISSUE TITLE
mvn repo?

### ISSUE THREAD

**Issue by egbutter** [leeadkins/elasticsearch-redis-river#4]
Hi Lee, 

It does not look like this is in a public repo (like, maven).  Did you ever try to do so?  

Your project seems to be working, and I'd love to use/support -- if I can automate build.  

Thanks, 

Eric

**Comment by leeadkins** [comment]
Hi Eric,

Sorry for the extremely delayed response. I must of just missed this a couple of weeks ago.

Getting this into something like maven isn't something I'd ever tried. When I originally wrote it, installing via github downloads was the common and supported way of doing things for these types of plugins. It worked for us, and is really how we're still doing it today.

However, I do recognize that in this day and age of Elasticsearch, it has become much more common to host artifacts in some sort of public repo. Which means at some point I probably need to tackle that, but it just isn't something I've had a chance to get into so far.

**Comment by egbutter** [comment]
Thanks, Lee!  I will throw it up on maven when I get the chance!  Cheers,
